name: Reusable workflow
on: 
  workflow_call:
    
    secrets:
      
      ghcr_username:
        required: false
      ghcr_token:
        required: false

  
jobs:
  artifact-upload:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
    - name: Login to GitHub Container registry
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Push Docker image
      run: |
          docker images 
          docker push ${{ needs.build.outputs.o-imagename }}
          docker images          
