name: Reusable workflow
on: 
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      password:
        required: false
jobs:
  artifact-upload:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}
        
    
    - name: Push Docker image
      run: |
          docker images
          docker push ${{needs.build.outputs.o-imagename}}
          docker images
