name: Reusable workflow
on: 
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      password:
        required: false

jobs:
  artifact-upload:
    runs-on: self-hosted
    steps:
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: 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
    
    - name: Push Docker image
      run: |
          docker images
          docker push ${{needs.build.outputs.o-imagename}}
          docker images  
