name: Reusable workflow
on: 
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      password:
        required: false

jobs:
  artifact-upload:
    runs-on: self-hosted 
    steps:
    - name: Push Docker image
      run: |
          docker images
          docker push ${{needs.build.outputs.o-imagename}}
          docker images
