name: Reusable workflow
on: 
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      password:
        required: false
jobs:
  artifact-upload:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
    - name: Push Docker image
      run: |
          echo "${{ secrets.GHCR_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
          docker images
          docker push ${{needs.build.outputs.o-imagename}}
          docker images
