name: Reusable workflow
on: 
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      password:
        required: false
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
jobs:
  artifact-upload:
    runs-on: self-hosted 
    steps:
    - name: Log into registry ${{ env.REGISTRY }}
      run: echo "${{ secrets.GHCR_PASSWORD }}" | docker login ghcr.io -u ${GITHUB_REPOSITORY,,} --password-stdin
    - name: Push Docker image
      run: |
          docker images
          docker push ${{needs.build.outputs.o-imagename}}
          docker images
