name: Reusable workflow
on: 
  workflow_call:
#permissions:
#  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        maven: [ '3.6.3' ]
        java: [ '11']
        
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Build with Maven
        run: mvn package
