name: Reusable workflow
on: 
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      password:
        required: false
jobs:
  build:
    runs-on: self-hosted
    outputs:
      o-imagename: ${{ steps.set-image-name.outputs.imagename }}

    strategy:
      matrix:
        maven: [ '3.6.3' ]
        java: [ '11']
        
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Set Image Name
        id: set-image-name
        run: |
            echo "IMAGE_NAME=${{ env.REGISTRY }}/${GITHUB_REPOSITORY,,}:$(git rev-parse --short HEAD)" >>${GITHUB_ENV}
            echo "::set-output name=imagename::ghcr.io/${GITHUB_REPOSITORY,,}:$(git rev-parse --short HEAD)"
      - name: Build with Maven
        run: mvn package
        
      - name: Edastakhat UI Build
        run: |
           docker --version
           docker images
           docker build -t ${{ env.IMAGE_NAME }} .
           docker images
