name: Reusable workflow
on: 
  workflow_call:
    outputs:
      o-imagename:
        description: "The first output string"
        value: ${{ jobs.build.outputs.o-imagename }}

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
permissions:
  contents: read
jobs:
  build:
    runs-on: self-hosted
    outputs:
      o-imagename: ${{ steps.set-image-name.outputs.imagename }}
    strategy:
      matrix:
        maven: [ '3.6.3' ]
        java: [ '11']
        
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Build with Maven
        run: mvn package
      - name: Set Image Name
        id: set-image-name
        run: |
            echo "IMAGE_NAME=${{ env.REGISTRY }}/${GITHUB_REPOSITORY,,}:$(git rev-parse --short HEAD)" >>${GITHUB_ENV}
            echo "::set-output name=o-imagename::${{ env.REGISTRY }}/${GITHUB_REPOSITORY,,}:$(git rev-parse --short HEAD)"
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
